class StaticPagesController < ApplicationController
  # generated by rails g controller StaticPages home help
  def home
    if logged_in?
      # Returns a new Micropost object associated with user
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help; end

  def about; end

  def contact; end
end
