class Micropost < ApplicationRecord
  # generated by rails g model Micropost content:text, user:references
  belongs_to :user
  # syntax for lambda or anonymous function which returns a Proc. Procs are eval with a call method
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end
