class Micropost < ApplicationRecord
  # generated by rails g model Micropost content:text, user:references
  belongs_to :user
  validates  :user_id, presence: true
  validates  :content, presence: true, length: { maximum: 140 }
end
